[package]
name = "fpopt"
version = "0.0.1"
edition = "2021"
description = "a wrapper around manipulating floating point flags"
license = "MIT"

[dependencies]
libc = "0.2.153"

[build-dependencies]
bindgen = "0.69.4"
